apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    service: backend-user
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend-user
  template:
    metadata:
      labels:
        service: backend-user
    spec:
      containers:
      - name: backend-user
        image: yhaw08/udagram-api-user:v2
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: example-configmap
              key: URL
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: example-configmap
              key: AWS_BUCKET
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: example-configmap
              key: AWS_PROFILE
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: example-configmap
              key: AWS_REGION
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: example-configmap
              key: JWT_SECRET
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: example-configmap
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: example-configmap
              key: POSTGRES_HOST
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: example-configmap
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USERNAME
          valueFrom:
            configMapKeyRef:
              name: example-configmap
              key: POSTGRES_USERNAME
        - name: ACCESS_KEY_ID
          valueFrom:
            configMapKeyRef:
              name: example-configmap
              key: ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              name: example-configmap
              key: AWS_SECRET_ACCESS_KEY
       