apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    service: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: yhaw08/udagram-api-feed:v1
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: example-configmap
          - secretRef:
              name: mysecret
        volumeMounts:
          - mountPath: "/root/.aws/"
            name: awssecret
      volumes:
      - name: awssecret
        configMap:
          name: awssecret
              